[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "algometa"
version = "0.0.1"
dependencies = ["typer", "numpy"]
scripts = { algometa = "algometa.main:app" }
optional-dependencies = { dev = [
    "pandas",
    "matplotlib",
    "seaborn",
    "plotly",
    "scipy",
    "statsmodels",
] }

[tool.setuptools.packages.find]
where = ["."]
include = ["algometa*"]
